#!/bin/bash

me=$(basename $0)

usage="

NAME
  ${me} - Prints a running total of a set of numbers. 

SYNOPSIS
  ${me} [OPTIONS] datafile
  ${me} < datafile
  cat datafile | ${me} 

DESCRIPTION
  ${me} Reads a list of numbers and adds them, displaying
  the running total. Useful for balancing a checkbook.

OPTIONS
  -h  Displays help message.

AUTHOR
  Berend M. Tober

"

infile="-"

while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h)
      echo "${usage}"
      exit
      ;;
    -*)
      echo "Invalid option '${1}'"
      exit
      ;;
  esac
  infile="${1--}"
  shift
done  

cat "${infile}" | awk '
{s=s+$1}
{printf("% 9.2f\t% 8.2f\t%3d\n",s,$1,NR)}
'
