#!/bin/bash

me=$(basename $0)

usage="

NAME
  ${me} - Discounted value of a series of cash flows.

SYNOPSIS
  ${me} [OPTIONS] datafile
  ${me} [OPTIONS] < datafile
  cat datafile | ${me} [OPTIONS] 

DESCRIPTION
  ${me} computes the discounted value of a stream of cash flow pairs
  (A,t) where the amount A of each pair is discounted for t time periods
  compounded. 

  Output is a list of ordered pairs (F,t) where F is the discounted 
  amount at time t.

OPTIONS
  -h  Displays help message.

  -i i
    Interest rate per period. Defaults to 0.

AUTHOR
  Berend M. Tober

"

i=0
infile="-"

while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h)
      echo "${usage}"
      exit
      ;;
    -i)
      i="${2}"
      shift 2
      ;;
    -*)
      echo "Invalid option '${1}'"
      exit
      ;;
  esac

  infile="${1--}"
  shift
done  

cat "${infile}" | awk -v i="$i" '
  {print $1/(1+i)^$2, $2};
'
